[package]
name = "kvell"
version = "0.1.0"
authors = ["Payne Zheng <3334248237@qq.com>"]
edition = "2018"
description = "A Fast Persistent Key-Value Store"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
